#!/usr/bin/env bash
#
# Stands up a throwaway webtrees with the mobile API module installed.
#
#   tool/lab/setup.sh 2.2.6 8622
#   tool/lab/setup.sh main  8623      # 2.3.0-dev, the working tree's branch
#   tool/lab/setup.sh 2.2.6 8622 1450 # ...and 1450 more invented people, which
#                                     # is what a sync of a real tree costs
#
# Everything lands under lab/ beside the upstream checkout, which is on the
# big volume rather than on / (which has under 2G free). Nothing here touches
# the app's own repository, and nothing here holds real family data: the tree
# is generated by tool/lab/make_gedcom.py and every person in it is invented.
#
# Re-running for the same version rebuilds the database from scratch and
# leaves the composer install alone, which is the slow part.

set -euo pipefail

REF="${1:-2.2.6}"
PORT="${2:-8622}"
# Extra invented people, for measuring what a whole-tree walk costs. Zero for
# every other purpose: the deliberate nineteen-person tree is the one the
# parsers and the transports are checked against.
BULK="${3:-0}"

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
UPSTREAM="$(cd "$HERE/../webtrees" && pwd)"
LAB="$HERE/../lab/webtrees-$REF"
BASE_URL="http://localhost:$PORT"

step() { printf '\n\033[1m==> %s\033[0m\n' "$*"; }

for tool in php composer python3; do
  command -v "$tool" >/dev/null || { echo "$tool is not installed"; exit 1; }
done

step "webtrees $REF -> $LAB"
if [ ! -d "$LAB/.git" ]; then
  mkdir -p "$(dirname "$LAB")"
  # A local clone: the objects are already on disk, so this costs no network
  # and no time, and the lab can then be checked out at any ref independently.
  git clone --quiet --shared "$UPSTREAM" "$LAB"
fi
git -C "$LAB" checkout --quiet --force "$REF"
git -C "$LAB" clean -qfd -e vendor -e data

step 'composer install'
if [ ! -f "$LAB/vendor/autoload.php" ]; then
  (cd "$LAB" && composer install --no-dev --no-interaction --quiet)
else
  echo "  already installed"
fi

step 'configuration'
mkdir -p "$LAB/data"
# Same shape as the file the setup wizard writes; see
# resources/views/setup/config.ini.phtml.
cat > "$LAB/data/config.ini.php" <<INI
; <?php return; ?> DO NOT DELETE THIS LINE
dbtype="sqlite"
dbhost=""
dbport=""
dbuser=""
dbpass=""
dbname="lab"
tblpfx="wt_"
dbkey=""
dbcert=""
dbca=""
dbverify=""
base_url="$BASE_URL"
rewrite_urls="0"
INI
echo "  base_url $BASE_URL"

# A clean database every run, so a failed import never leaves half a tree
# behind to be mistaken for a parser bug.
rm -f "$LAB/data/lab.sqlite"
touch "$LAB/data/lab.sqlite"

step 'the module'
mkdir -p "$LAB/modules_v4"
rm -rf "$LAB/modules_v4/webtrees-mobile-api"
# A symlink, so editing the module in the repository takes effect immediately
# in both labs without copying anything.
ln -s "$HERE/server/webtrees-mobile-api" "$LAB/modules_v4/webtrees-mobile-api"
echo "  linked $LAB/modules_v4/webtrees-mobile-api"

step 'synthetic tree'
python3 "$HERE/tool/lab/make_gedcom.py" --bulk "$BULK" > "$LAB/data/lab.ged"
echo "  $(wc -l < "$LAB/data/lab.ged") lines, entirely invented"
# `set -e` is on, so this is an `if` and not a `&&`: a false test on the last
# command of a line would abort the script.
if [ "$BULK" -gt 0 ]; then
  echo "  including $BULK bulk people — not the tree to test parsers against"
fi

step 'install'
php "$HERE/tool/lab/install.php" "$LAB" "$LAB/data/lab.ged" "$BASE_URL"

step 'ready'
cat <<DONE
  Serve it:   php -S localhost:$PORT -t "$LAB" "$LAB/index.php"
  Check it:   WEBTREES_PASSWORD=lab-member-password \\
                dart run tool/live_check.dart --url localhost:$PORT --user mobile
DONE
